### ISSUE TITLE
Design component for post

### ISSUE THREAD

**Issue by Hanif-adedotun** [Startvest/interna#15]
![post component](https://user-images.githubusercontent.com/54331442/189584872-e18381ed-d56e-4e73-a5b7-38bb4c911ac5.png)

The dummy data will be located in _services/enums/_ folder

The modals for comment and share can also be created, it can be a sub_component in the modal component folder

**Comment by Hanif-adedotun** [comment]
To use the Display date component I made, 

 <DisplayDate date={"Mon Sep 9 2022 17:55:34 GMT+0100 (West Africa Standard Time)"} show={"ago"}/>

**Comment by fortune710** [comment]
80% percent done with it and committed the changes. Just need to check the colors on light mode and that should be all

**Comment by fortune710** [comment]
Finally done...made a Toolbar component in the Process. In the /test-post route, you can see the different posts, tapping the image would lead you to a detail page...

**Comment by Hanif-adedotun** [comment]
Okay, very wonderful job Fortune

**Comment by Hanif-adedotun** [comment]
So you can pick any page you want to integrate next, maybe the profile page, your choice...
